### ISSUE TITLE
ReferenceError: document is not defined

### ISSUE THREAD

**Issue by tomasite** [troybetz/react-youtube#55]
Hi, first thanks for your react component!
I just have one problem when I try import it in my react webapp. Note sure if it's caused by react-youtube itself or just a problem of configuration in my app (created with https://github.com/koistya/react-static-boilerplate) but here is the stacktrace:
```
Starting 'render'...
ReferenceError: document is not defined
    at load ([..]/webapp/node_modules/load-script/index.js:3:14)
    at exports.default ([..]/webapp/node_modules/youtube-player/dist/es5/loadYouTubeIframeAPI.js:43:33)
    at Object.<anonymous> ([..]/webapp/node_modules/youtube-player/dist/es5/index.js:41:58)
    at Module._compile (module.js:434:26)
    at Module._extensions..js (module.js:452:10)
    at Object.require.extensions.(anonymous function) [as .js] ([..]/webapp/node_modules/babel-core/lib/api/register/node.js:214:7)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Module.require (module.js:365:17)
    at require (module.js:384:17)
    at Object.<anonymous> ([..]/webapp/node_modules/react-youtube/dist/YouTube.js:23:22)
    at Module._compile (module.js:434:26)
    at Module._extensions..js (module.js:452:10)
    at Object.require.extensions.(anonymous function) [as .js] ([..]/webapp/node_modules/babel-core/lib/api/register/node.js:214:7)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
```
(I already tried to escape the serve side rendering with a canUseDom check but it changes nothing, the error occurs during the import..)

Thanks in advance for your help!
Thomas

**Comment by tjallingt** [comment]
Hey @tomasite,

Can you please give some more information on the issue such as:
- what actions cause this issue (seems to be `npm start` of the boilerplate)?
- which version of `react-youtube` are you using (please use the latest version)?
- can you give some more context on how you are using `react-youtube` in your application?

Sadly I can't tell much from the stack trace but the issue seems more likely to be related to the configuration of your application than `react-youtube`.
I'll see if I can help a little anyway if you answer the questions above :smile:.

I'll close the issue for now but if it appears to be directly related to `react-youtube` we'll reopen it.

**Comment by tomasite** [comment]
Hey @tjallingt,
thanks for your answer! here are some clues:
1) it's right after ```npm start``` of the boilerplate indeed,
2) I'am using the last version at this moment (5.0.0),
3) here is a snippet of how I use react-youtube:
```
import React, { Component } from 'react';
import YouTube from 'react-youtube';

export default class extends Component {

  render() {

    return (
      <div>
        <h1>Home Page</h1>
        <p>Coming soon.</p>
        <Youtube
          videoId='2g811Eo7K8U'
          playbackState='unstarted'
          configuration={
              {
                  showinfo: 0,
                  controls: 0
              }
          }
        />
      </div>
    );
  }

}
```
Thanks again,
Thomas
