### ISSUE TITLE
global is not defined 

### ISSUE THREAD

**Issue by sylvainlap** [troybetz/react-youtube#61]
Hi,

I wanted to try your lib thanks to `npm install react-youtube` and `npm run example`, but when I try to hit `localhost:8080`, I got this error in the browser console:

```
Unhandled rejection ReferenceError: global is not defined
    at _bluebird2.default.resolve (http://localhost:8080/build/bundle.js:27942:21)
    at exports.default (http://localhost:8080/build/bundle.js:27939:23)
    at exports.default (http://localhost:8080/build/bundle.js:22388:60)
    at YouTube.createPlayer (http://localhost:8080/build/bundle.js:19930:59)
    at YouTube.componentDidMount (http://localhost:8080/build/bundle.js:19847:13)
    at CallbackQueue.assign.notifyAll (http://localhost:8080/build/bundle.js:6501:23)
    at ReactReconcileTransaction.ON_DOM_READY_QUEUEING.close (http://localhost:8080/build/bundle.js:16255:27)
    at ReactReconcileTransaction.Mixin.closeAll (http://localhost:8080/build/bundle.js:6862:26)
    at ReactReconcileTransaction.Mixin.perform (http://localhost:8080/build/bundle.js:6809:17)
    at batchedMountComponentIntoNode (http://localhost:8080/build/bundle.js:2709:16)
    at ReactDefaultBatchingStrategyTransaction.Mixin.perform (http://localhost:8080/build/bundle.js:6796:21)
    at Object.ReactDefaultBatchingStrategy.batchedUpdates (http://localhost:8080/build/bundle.js:10829:20)
    at Object.batchedUpdates (http://localhost:8080/build/bundle.js:6301:21)
```

Any idea ?

**Comment by tjallingt** [comment]
Can you supply more information?
What browser are you using? What operating system? What does the command line output?

**Comment by sylvainlap** [comment]
It's ok, the error was from youtube-player, and has been resolved: https://github.com/gajus/youtube-player/issues/5
