### ISSUE TITLE
_onReady event not firing anymore in Chrome

### ISSUE THREAD

**Issue by coded-aesthetics** [troybetz/react-youtube#98]
I am aware that this is most likely not a problem by the react-youtube player component itself. 
The error occurs in this file that is used by the react-youtube player:
`https://www.youtube.com/yts/jsbin/player-de_DE-vflM_cNgA/base.js`

I just wanted to check if anybody else is experiencing this problem...

This is the error I get upon initialization of the react-youtube component:
```
Uncaught TypeError: a.g.setActionHandler is not a function
    at J_ (https://www.youtube.com/yts/jsbin/player-de_DE-vflM_cNgA/base.js:3784:24)
    at new K_ (https://www.youtube.com/yts/jsbin/player-de_DE-vflM_cNgA/base.js:3779:111)
    at new Y1 (https://www.youtube.com/yts/jsbin/player-de_DE-vflM_cNgA/base.js:3974:367)
    at new d2 (https://www.youtube.com/yts/jsbin/player-de_DE-vflM_cNgA/base.js:3995:210)
    at d2.create (https://www.youtube.com/yts/jsbin/player-de_DE-vflM_cNgA/base.js:6993:333)
    at Gi.<anonymous> (https://www.youtube.com/yts/jsbin/www-embed-player-vfl-i_LLs/www-embed-player.js:507:269)
    at Gi.l.jb (https://www.youtube.com/yts/jsbin/www-embed-player-vfl-i_LLs/www-embed-player.js:507:308)
    at Ki (https://www.youtube.com/yts/jsbin/www-embed-player-vfl-i_LLs/www-embed-player.js:505:143)
    at Gi.l.oa (https://www.youtube.com/yts/jsbin/www-embed-player-vfl-i_LLs/www-embed-player.js:498:176)
    at https://www.youtube.com/yts/jsbin/www-embed-player-vfl-i_LLs/www-embed-player.js:557:378 
```

Will check if the error persists, and update this issue accordingly.

**Comment by coded-aesthetics** [comment]
Okay, this went away... must have been a temporary error in one of the youtube-api scripts...

**Comment by tjallingt** [comment]
Yea the error stack seems to indicate that this problem was caused on YouTube's end.
You already closed the issue but if it persists in the future feel free to reopen it.

**Comment by ahmetozalp** [comment]
base.js:30 Uncaught TypeError: Cannot read property 'prototype' of undefined
    at Object.g.p (base.js:30)
    at remote.js:79
    at remote.js:162
g.p @ base.js:30
(anonymous) @ remote.js:79
(anonymous) @ remote.js:162
annotations_module.js:419 Uncaught TypeError: Cannot read property 'prototype' of undefined
    at annotations_module.js:419
    at annotations_module.js:697
